'use client'

import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function Auth() { const supabase = createClient(); const [mode, setMode] = useState<'login' | 'signup'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setNotice(''); if (mode === 'signup') { const { error } = await supabase.auth.signUp({ email, password, options: { data: { display_name: name || email.split('@')[0] } } }); setNotice(error?.message || 'Check your email to confirm your account.') } else { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) setNotice(error.message); else location.reload() } setBusy(false) }
  return <section className="auth"><div className="intro"><p className="eyebrow">A quieter place to talk</p><h1>Stay in the loop.</h1><p>Simple, fast messaging for the people and communities that matter.</p></div><form onSubmit={submit}><h2>{mode === 'login' ? 'Welcome back' : 'Create your account'}</h2>{mode === 'signup' && <input required value={name} onChange={e => setName(e.target.value)} placeholder="Display name" /> }<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email address" /><input required minLength={6} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" /><button className="primary" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Log in' : 'Sign up'}</button>{notice && <p className="notice">{notice}</p>}<button type="button" className="switch" onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Log in'}</button></form></section>
}
